import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';
import { ScrollArea } from '@/components/ui/scroll-area';
import ThemeProvider from '@/components/theme-provider';
import Header from '@/components/header';
import Footer from '@/components/footer';
import '@/app/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Movie Tracker',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang='en' suppressHydrationWarning>
        <body className={inter.className}>
          <ThemeProvider attribute='class'>
            <ScrollArea type='auto' className='h-screen'>
              <div className='min-h-screen flex flex-col'>
                <Header />
                {children}
                <Footer />
              </div>
            </ScrollArea>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
