import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ThemeProvider from '@/components/subcomponents/theme-provider';
import Footer from '@/components/subcomponents/footer';
import Header from '@/components/subcomponents/header';
import { ClerkProvider } from '@clerk/nextjs';
// import { ScrollArea } from '@/components/ui/scroll-area';
import '@/app/globals.css';
import { UserDataProvider } from '@/context/userData';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Movie Tracker',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang='en' suppressHydrationWarning>
        <head>
          <meta name='theme-color' media='(prefers-color-scheme: light)' content='white' />
          <meta name='theme-color' media='(prefers-color-scheme: dark)' content='black' />
        </head>
        <body className={inter.className}>
          <ThemeProvider attribute='class'>
            <UserDataProvider>
              <Header />
              {children}
              <Footer />
            </UserDataProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
